force-app/main/default/objects/String_Nesting_Mapping__mdt/String_Nesting_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Stores Mappings for opening &amp; closing brackets.</description>
    <label>String Nesting Mapping</label>
    <pluralLabel>String Nesting Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/String_Nesting_Mapping__mdt/fields/Closing_Bracket__c.field-meta.xml
<CustomField>
    <fullName>Closing_Bracket__c</fullName>
    <label>Closing Bracket</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/String_Nesting_Mapping__mdt/fields/Opening_Bracket__c.field-meta.xml
<CustomField>
    <fullName>Opening_Bracket__c</fullName>
    <label>Opening Bracket</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Super_Users__c/Super_Users__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Super Users</label>
</CustomObject>

force-app/main/default/objects/Super_Users__c/fields/Save_Invalid_Widgets__c.field-meta.xml
<CustomField>
    <fullName>Save_Invalid_Widgets__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Save Invalid Widgets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Widget__c/Widget__c.object-meta.xml
<CustomObject>
    <description>Stores widget information</description>
    <label>Widget</label>
    <nameField>
        <displayFormat>W-{00000}</displayFormat>
        <label>Widget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/WidgetCreationClass.cls
/***********************************************************************************************
ClassName   : WidgetCreationClass
Description : Class for performing server-side actions for createWidgetRecordComponent.
Author      : Neha Dave

Version History :
Author      Date         Description
Neha Dave   04-07-2021   Initial Draft of controller class.
Neha Dave   04-07-2021   Added method to fetch Metadata & create widget records.
************************************************************************************************/
public with sharing class WidgetCreationClass {


    /*************************************************************************
     Method Name : fetchNestingMappingRecords
     Description : Method to fetch String_Nesting_Mapping__mdt and return list
                   to the Js controller of createWidgetRecordComponent.
          Author : Neha Dave
    **************************************************************************/
    @AuraEnabled( cacheable=true )
    public static List <String_Nesting_Mapping__mdt> fetchNestingMappingRecords() {
        return [ SELECT Id
                      , MasterLabel
                      , Closing_Bracket__c
                      , Opening_Bracket__c
                  FROM String_Nesting_Mapping__mdt
                ];
    }

    /*************************************************************************
     Method Name : fetchSuperUserDetails
     Description : Method to check if the current user is a super user.
          Author : Neha Dave
    **************************************************************************/
    @AuraEnabled( cacheable=true )
    public static Boolean fetchSuperUserDetails() {
        return Super_Users__c.getinstance().Save_Invalid_Widgets__c;
    }

    /*************************************************************************
     Method Name : createWidgetRecord
     Description : Method to create Widget record.
          Author : Neha Dave
    **************************************************************************/
    @AuraEnabled
    public static Widget__c createWidgetRecord(Widget__c widObj){
        System.debug('createWidgetRecord'+widObj);
        try {
            insert widObj;
            return widObj;
        } catch (Exception exp) {
            throw new AuraHandledException(exp.getMessage());
        }
    }

}